/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by prisma/seed/_genPracticeCatalog.ts
 */
export const GENERATED_CATALOG = {
  "python": {
    "subjectSlug": "python",
    "modulesBySlug": {
      "python-0": {
        "moduleSlug": "python-0",
        "sectionSlug": "python-0-foundations",
        "sectionTitle": "Python 0 — Foundations",
        "sectionOrder": 0,
        "genKey": "python_part1",
        "prefix": "py0",
        "topicIds": [
          "print",
          "io_vars",
          "strings",
          "math_precedence",
          "comments_errors",
          "foundations"
        ],
        "topics": {
          "print": "py0.print",
          "io_vars": "py0.io_vars",
          "strings": "py0.strings",
          "math_precedence": "py0.math_precedence",
          "comments_errors": "py0.comments_errors",
          "foundations": "py0.foundations"
        }
      }
    }
  },
  "linear-algebra": {
    "subjectSlug": "linear-algebra",
    "modulesBySlug": {
      "linear-algebra-0": {
        "moduleSlug": "linear-algebra-0",
        "sectionSlug": "linear-algebra-0-vectors",
        "sectionTitle": "Linear Algebra 0 — Vectors",
        "sectionOrder": 0,
        "genKey": "linear_algebra_mod0",
        "prefix": "la0",
        "topicIds": [
          "dot",
          "vectors",
          "angle",
          "projection",
          "vectors_part1",
          "vectors_part2"
        ],
        "topics": {
          "dot": "la0.dot",
          "vectors": "la0.vectors",
          "angle": "la0.angle",
          "projection": "la0.projection",
          "vectors_part1": "la0.vectors_part1",
          "vectors_part2": "la0.vectors_part2"
        }
      },
      "linear-algebra-1": {
        "moduleSlug": "linear-algebra-1",
        "sectionSlug": "linear-algebra-1-linear-systems",
        "sectionTitle": "Linear Algebra 1 — Linear Systems",
        "sectionOrder": 10,
        "genKey": "linear_algebra_mod1",
        "prefix": "la1",
        "topicIds": [
          "linear_systems",
          "augmented",
          "rref",
          "solution_types",
          "parametric"
        ],
        "topics": {
          "linear_systems": "la1.linear_systems",
          "augmented": "la1.augmented",
          "rref": "la1.rref",
          "solution_types": "la1.solution_types",
          "parametric": "la1.parametric"
        }
      },
      "linear-algebra-2": {
        "moduleSlug": "linear-algebra-2",
        "sectionSlug": "linear-algebra-2-matrices-part-1",
        "sectionTitle": "Linear Algebra 2 — Matrices (Part 1)",
        "sectionOrder": 20,
        "genKey": "linear_algebra_mod2",
        "prefix": "la2",
        "topicIds": [
          "matrix_ops",
          "matrix_inverse",
          "matrix_properties",
          "matrices_intro",
          "index_slice",
          "special",
          "elementwise_shift",
          "matmul",
          "matvec",
          "transpose_liveevil",
          "symmetric",
          "matrices_part1_mix"
        ],
        "topics": {
          "matrix_ops": "la2.matrix_ops",
          "matrix_inverse": "la2.matrix_inverse",
          "matrix_properties": "la2.matrix_properties",
          "matrices_intro": "la2.matrices_intro",
          "index_slice": "la2.index_slice",
          "special": "la2.special",
          "elementwise_shift": "la2.elementwise_shift",
          "matmul": "la2.matmul",
          "matvec": "la2.matvec",
          "transpose_liveevil": "la2.transpose_liveevil",
          "symmetric": "la2.symmetric",
          "matrices_part1_mix": "la2.matrices_part1_mix"
        }
      },
      "linear-algebra-3": {
        "moduleSlug": "linear-algebra-3",
        "sectionSlug": "linear-algebra-3-matrices-part-2",
        "sectionTitle": "Linear Algebra 3 — Matrices (Part 2)",
        "sectionOrder": 30,
        "genKey": "linear_algebra_mod3",
        "prefix": "la3",
        "topicIds": [
          "norms",
          "colspace",
          "nullspace",
          "rank",
          "det",
          "charpoly",
          "matrices_part2_mix"
        ],
        "topics": {
          "norms": "la3.norms",
          "colspace": "la3.colspace",
          "nullspace": "la3.nullspace",
          "rank": "la3.rank",
          "det": "la3.det",
          "charpoly": "la3.charpoly",
          "matrices_part2_mix": "la3.matrices_part2_mix"
        }
      }
    }
  }
}
;
export type GeneratedCatalog = typeof GENERATED_CATALOG;
