/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by prisma/seed/_genPracticeCatalog.ts
 */
export const GENERATED_CATALOG = {
  "python": {
    "subjectSlug": "python",
    "modulesBySlug": {
      "python-0": {
        "moduleSlug": "python-0",
        "sectionSlug": "python-0-foundations",
        "sectionTitle": "Python 0 — Foundations",
        "sectionOrder": 0,
        "genKey": "python_part1",
        "prefix": "py0",
        "topicIds": [
          "print",
          "io_vars",
          "strings",
          "math_precedence",
          "comments_errors",
          "foundations"
        ],
        "topics": {
          "print": "py0.print",
          "io_vars": "py0.io_vars",
          "strings": "py0.strings",
          "math_precedence": "py0.math_precedence",
          "comments_errors": "py0.comments_errors",
          "foundations": "py0.foundations"
        }
      }
    }
  },
  "linear-algebra": {
    "subjectSlug": "linear-algebra",
    "modulesBySlug": {
      "linear-algebra-0": {
        "moduleSlug": "linear-algebra-0",
        "sectionSlug": "linear-algebra-0-vectors",
        "sectionTitle": "Linear Algebra 0 — Vectors",
        "sectionOrder": 0,
        "genKey": "linear_algebra_mod0",
        "prefix": "la0",
        "topicIds": [
          "dot",
          "vectors",
          "angle",
          "projection",
          "vectors_part1",
          "vectors_part2"
        ],
        "topics": {
          "dot": "la0.dot",
          "vectors": "la0.vectors",
          "angle": "la0.angle",
          "projection": "la0.projection",
          "vectors_part1": "la0.vectors_part1",
          "vectors_part2": "la0.vectors_part2"
        }
      },
      "linear-algebra-1": {
        "moduleSlug": "linear-algebra-1",
        "sectionSlug": "linear-algebra-1-linear-systems",
        "sectionTitle": "Linear Algebra 1 — Linear Systems",
        "sectionOrder": 10,
        "genKey": "linear_algebra_mod1",
        "prefix": "la1",
        "topicIds": [
          "linear_systems",
          "augmented",
          "rref",
          "solution_types",
          "parametric"
        ],
        "topics": {
          "linear_systems": "la1.linear_systems",
          "augmented": "la1.augmented",
          "rref": "la1.rref",
          "solution_types": "la1.solution_types",
          "parametric": "la1.parametric"
        }
      },
      "linear-algebra-2": {
        "moduleSlug": "linear-algebra-2",
        "sectionSlug": "linear-algebra-2-matrices-part-1",
        "sectionTitle": "Linear Algebra 2 — Matrices (Part 1)",
        "sectionOrder": 20,
        "genKey": "linear_algebra_mod2",
        "prefix": "la2",
        "topicIds": [
          "matrix_ops",
          "matrix_inverse",
          "matrix_properties",
          "matrices_intro",
          "index_slice",
          "special",
          "elementwise_shift",
          "matmul",
          "matvec",
          "transpose_liveevil",
          "symmetric",
          "matrices_part1_mix"
        ],
        "topics": {
          "matrix_ops": "la2.matrix_ops",
          "matrix_inverse": "la2.matrix_inverse",
          "matrix_properties": "la2.matrix_properties",
          "matrices_intro": "la2.matrices_intro",
          "index_slice": "la2.index_slice",
          "special": "la2.special",
          "elementwise_shift": "la2.elementwise_shift",
          "matmul": "la2.matmul",
          "matvec": "la2.matvec",
          "transpose_liveevil": "la2.transpose_liveevil",
          "symmetric": "la2.symmetric",
          "matrices_part1_mix": "la2.matrices_part1_mix"
        }
      },
      "linear-algebra-3": {
        "moduleSlug": "linear-algebra-3",
        "sectionSlug": "linear-algebra-3-matrices-part-2",
        "sectionTitle": "Linear Algebra 3 — Matrices (Part 2)",
        "sectionOrder": 30,
        "genKey": "linear_algebra_mod3",
        "prefix": "la3",
        "topicIds": [
          "norms",
          "colspace",
          "nullspace",
          "rank",
          "det",
          "charpoly",
          "matrices_part2_mix"
        ],
        "topics": {
          "norms": "la3.norms",
          "colspace": "la3.colspace",
          "nullspace": "la3.nullspace",
          "rank": "la3.rank",
          "det": "la3.det",
          "charpoly": "la3.charpoly",
          "matrices_part2_mix": "la3.matrices_part2_mix"
        }
      },
      "linear-algebra-4": {
        "moduleSlug": "linear-algebra-4",
        "sectionSlug": "linear-algebra-4-orthogonality",
        "sectionTitle": "Linear Algebra 4 — Inner Products & Orthogonality",
        "sectionOrder": 40,
        "genKey": "linear_algebra_mod4",
        "prefix": "la4",
        "topicIds": [
          "norms2",
          "inner_products",
          "angles_orthogonality",
          "projection_line",
          "projection_matrix",
          "onb",
          "orthogonal_matrices",
          "gram_schmidt",
          "weighted_inner_product",
          "spd",
          "lengths_distances",
          "orthogonal_complement",
          "inner_product_functions",
          "projection_subspace",
          "projection_affine",
          "rotations",
          "mod4_mix"
        ],
        "topics": {
          "norms2": "la4.norms2",
          "inner_products": "la4.inner_products",
          "angles_orthogonality": "la4.angles_orthogonality",
          "projection_line": "la4.projection_line",
          "projection_matrix": "la4.projection_matrix",
          "onb": "la4.onb",
          "orthogonal_matrices": "la4.orthogonal_matrices",
          "gram_schmidt": "la4.gram_schmidt",
          "weighted_inner_product": "la4.weighted_inner_product",
          "spd": "la4.spd",
          "lengths_distances": "la4.lengths_distances",
          "orthogonal_complement": "la4.orthogonal_complement",
          "inner_product_functions": "la4.inner_product_functions",
          "projection_subspace": "la4.projection_subspace",
          "projection_affine": "la4.projection_affine",
          "rotations": "la4.rotations",
          "mod4_mix": "la4.mod4_mix"
        }
      }
    }
  },
  "haitian-creole": {
    "subjectSlug": "haitian-creole",
    "modulesBySlug": {
      "haitian-creole-0": {
        "moduleSlug": "haitian-creole-0",
        "sectionSlug": "haitian-creole-0-foundations",
        "sectionTitle": "Haitian Creole 0 — Foundations",
        "sectionOrder": 0,
        "genKey": "haitian_creole_part1",
        "prefix": "hc0",
        "topicIds": [
          "greetings",
          "pronouns",
          "simple_sentences",
          "numbers",
          "everyday_phrases",
          "foundations"
        ],
        "topics": {
          "greetings": "hc0.greetings",
          "pronouns": "hc0.pronouns",
          "simple_sentences": "hc0.simple_sentences",
          "numbers": "hc0.numbers",
          "everyday_phrases": "hc0.everyday_phrases",
          "foundations": "hc0.foundations"
        }
      }
    }
  },
  "ai": {
    "subjectSlug": "ai",
    "modulesBySlug": {
      "ai-0": {
        "moduleSlug": "ai-0",
        "sectionSlug": "ai-0-kickstart-genai-foundations",
        "sectionTitle": "Module 0 — Setup + Safety Gate",
        "sectionOrder": 0,
        "genKey": "ai_mod0",
        "prefix": "ai0",
        "topicIds": [
          "capabilities",
          "workflow",
          "asking_format",
          "dont_paste",
          "redaction",
          "data_controls",
          "lab_ui",
          "lab_prompt",
          "lab_submit"
        ],
        "topics": {
          "capabilities": "ai0.capabilities",
          "workflow": "ai0.workflow",
          "asking_format": "ai0.asking_format",
          "dont_paste": "ai0.dont_paste",
          "redaction": "ai0.redaction",
          "data_controls": "ai0.data_controls",
          "lab_ui": "ai0.lab_ui",
          "lab_prompt": "ai0.lab_prompt",
          "lab_submit": "ai0.lab_submit"
        }
      }
    }
  }
}
;
export type GeneratedCatalog = typeof GENERATED_CATALOG;
